In [5]:
"""
    Author: Xu Jingshen
    Time: 2022/03/16
"""
import numpy as np 
from scipy.optimize import minimize

def eqn(X):
    return X@X + 2          #“@”表示矩阵相乘
X0 = np.asarray((1, 1))

mymin = minimize(fun=eqn, x0 = X0, method = "BFGS")
print(mymin)

"""
e = 1e-10 # 非常接近0的值
fun = lambda x : (x[0] - 0.667) / (x[0] + x[1] + x[2] - 2) # 约束函数

cons = ({'type': 'eq', 'fun': lambda x: x[0] * x[1] * x[2] - 1}, # xyz=1
        {'type': 'ineq', 'fun': lambda x: x[0] - e}, # x>=e，即 x > 0
        {'type': 'ineq', 'fun': lambda x: x[1] - e},
        {'type': 'ineq', 'fun': lambda x: x[2] - e}
       )
x0 = np.array((1.0, 1.0, 1.0)) # 设置初始值
res = minimize(fun, x0, method='SLSQP', constraints = cons)
print(res)
#print('最小值：',res.fun)
#print('最优解：',res.x)
#print('迭代终止是否成功：', res.success)
#print('迭代终止原因：', res.message)
"""



      fun: 2.0000000000000013
 hess_inv: array([[ 0.75000001, -0.24999999],
       [-0.24999999,  0.75000001]])
      jac: array([-5.96046448e-08, -5.96046448e-08])
  message: 'Optimization terminated successfully.'
     nfev: 9
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([-2.37910001e-08, -2.37910001e-08])


In [39]:
from scipy.optimize import minimize
import pandas as pd 
import numpy as np


##Objective Function
def MSE(S, dc):
    """
    params:
        S: Stoichiometric Matrix (Matrix) 
        dc: Changes of concentrations (vector) unit(mol/(L * min))
    return: object function(MSE here)
    """
    def v(x):
        """
        params:
            x: Velocity of Chemical reaction (vector)
        return:
        """
        return np.linalg.norm((S@x-dc), ord = 2)**2 / (S.shape[1])          #1/m * (S@x - dc)**2
    return v

np.random.seed(42)
S =  np.random.randint(low = 0, high = 3, size = (10,20))                  #Stoichiometric Matrix
dc =  np. random.rand(10)                       #Changes of concentration
k  = 2/3                                        #ratio of carbonhydrate to lipid  

print(S)
print(dc)



e = 1e-10       #非常接近0的值
cons = ({'type': 'eq', 'fun': lambda x: x[0] + x[1] - k * x[2]}) # x+y = k(z)
       

#x0 = np.zeros(v.shape[0])      #全零
np.random.seed(42)
x0 = np.random.rand(S.shape[1])      #随机初始值

res = minimize(MSE(S, dc), x0, method='SLSQP', constraints = cons)
print(res)

[[2 0 2 2 0 0 2 1 2 2 2 2 0 2 1 0 1 1 1 1]
 [0 0 1 1 0 0 0 2 2 2 1 2 1 1 2 1 2 2 0 2]
 [0 2 2 0 0 2 1 0 1 1 1 0 1 0 1 2 2 0 2 2]
 [1 0 1 1 1 1 1 1 1 0 2 1 1 1 1 1 1 2 2 1]
 [2 0 1 0 0 1 2 0 1 0 0 0 0 2 0 0 0 2 0 0]
 [2 2 2 0 2 2 0 2 0 1 2 1 0 2 0 1 0 2 2 1]
 [0 2 1 2 2 0 2 0 2 1 2 0 0 1 2 2 1 2 2 0]
 [2 2 1 1 0 2 2 2 0 0 1 0 2 2 0 2 2 0 0 2]
 [2 2 1 1 1 0 1 0 0 1 1 1 2 1 2 0 2 1 0 0]
 [0 2 1 0 0 0 2 2 1 2 0 1 0 0 2 1 2 2 1 0]]
[0.40383617 0.06489225 0.25391541 0.24687606 0.69630427 0.71227059
 0.14808693 0.99774049 0.26678101 0.97661496]
     fun: 6.863394113995715e-07
     jac: array([ 7.79995975e-05,  3.90859214e-04, -7.04754178e-05,  2.98714674e-04,
        1.17347684e-04, -1.71260358e-04,  1.93013623e-04,  1.57754021e-04,
       -6.01396779e-05,  1.41828358e-04,  3.83911799e-05, -1.34149133e-04,
       -1.73655731e-04,  2.19043613e-04, -1.24959512e-04,  1.23909931e-04,
       -9.42028108e-05, -2.97888715e-04, -2.36985510e-04, -1.25695520e-04])
 message: 'Optimization terminated suc

In [31]:
X = np.asarray((2, 2))
np.linalg.norm(X, ord=2)**2
print(np.array((1, 1, 1)).shape)
print(np.zeros(3).shape[0])

np.random.seed(42)
np.random.rand(3)


(3,)
3


array([0.37454012, 0.95071431, 0.73199394])